"""
IAP Browser Authentication for DefectDojo

Uses Playwright to open a real browser for Google/IAP login.
After the user authenticates, cookies are extracted automatically
and cached for use in curl -b API calls.

No manual cookie copying needed. No IAP_CLIENT_ID or IAP_CLIENT_SECRET required.

Flow:
1. Check for cached cookies in ~/.defectdojo/iap_cookies.txt
2. If expired/missing → launch Playwright browser to DEFECTDOJO_URL
3. Wait for user to complete Google login (IAP handles OAuth)
4. Detect successful login (URL returns to DefectDojo domain)
5. Extract all cookies from browser context automatically
6. Save in Netscape cookie jar format for curl -b
7. Close browser

Env vars: DEFECTDOJO_URL (required)
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

CACHE_DIR = Path.home() / ".defectdojo"
COOKIE_CACHE_FILE = CACHE_DIR / "iap_cookies.txt"
COOKIE_META_FILE = CACHE_DIR / "iap_cookies_meta.json"

# IAP session cookies typically last ~1 hour
DEFAULT_TTL = 3600


def _ensure_cache_dir() -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)


def get_cached_cookies() -> Optional[str]:
    """Return path to cached cookie file if still valid."""
    if not COOKIE_CACHE_FILE.exists() or not COOKIE_META_FILE.exists():
        return None
    try:
        meta = json.loads(COOKIE_META_FILE.read_text())
        if meta.get("expires_at", 0) > time.time() + 60:
            return str(COOKIE_CACHE_FILE)
    except (json.JSONDecodeError, KeyError):
        pass
    return None


def _save_cookies(cookies: list, domain: str, ttl: int = DEFAULT_TTL) -> str:
    """Save browser cookies in Netscape cookie jar format for curl -b."""
    _ensure_cache_dir()

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by iap_browser_auth.py (Playwright)",
        "",
    ]

    cookie_names = []
    for c in cookies:
        cookie_domain = c.get("domain", domain)
        name = c["name"]
        # __Host- cookies are host-only: no leading dot, flag = FALSE
        if name.startswith("__Host-"):
            cookie_domain = cookie_domain.lstrip(".")
            domain_flag = "FALSE"
        else:
            if not cookie_domain.startswith("."):
                cookie_domain = "." + cookie_domain
            domain_flag = "TRUE"
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = max(0, int(c.get("expires", 0)))  # -1 → 0 (session cookie)
        path = c.get("path", "/")
        value = c["value"]
        lines.append(f"{cookie_domain}\t{domain_flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
        cookie_names.append(name)

    COOKIE_CACHE_FILE.write_text("\n".join(lines) + "\n")
    COOKIE_CACHE_FILE.chmod(0o600)

    COOKIE_META_FILE.write_text(json.dumps({
        "expires_at": time.time() + ttl,
        "domain": domain,
        "cookie_names": cookie_names,
    }))
    COOKIE_META_FILE.chmod(0o600)

    return str(COOKIE_CACHE_FILE)


def _validate_cookies(cookie_file: str, dd_url: str) -> bool:
    """Test if cookies work against DefectDojo (passes IAP)."""
    try:
        result = subprocess.run(
            ["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
             "-b", cookie_file, f"{dd_url}/api/v2/"],
            capture_output=True, text=True, timeout=15
        )
        status = result.stdout.strip()
        # 200 = full access, 403 = past IAP but auth issue, both mean IAP cookies work
        return status in ("200", "301", "302", "403")
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False


def browser_login(dd_url: str) -> str:
    """
    Launch Playwright browser for IAP login, extract cookies automatically.

    Opens a visible browser window to DefectDojo. IAP redirects to Google login.
    After user authenticates, detects redirect back to DefectDojo and extracts cookies.

    Returns path to cookie jar file.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("ERROR: playwright not installed. Run: pip install playwright && playwright install", file=sys.stderr)
        sys.exit(1)

    domain = dd_url.replace("https://", "").replace("http://", "").split("/")[0]

    print(f"Launching browser for IAP login at {dd_url} ...")
    print("Complete the Google login in the browser window.\n")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()

        page.goto(dd_url, wait_until="domcontentloaded")

        # Wait until we're back on the DefectDojo domain (IAP login complete)
        # The page URL will contain the DefectDojo domain after successful auth
        try:
            page.wait_for_url(f"**{domain}**", timeout=120_000)

            # Give a moment for all cookies to be set
            page.wait_for_timeout(2000)

            # Also wait for the page to be actually loaded (not a redirect)
            page.wait_for_load_state("networkidle", timeout=15_000)
        except Exception:
            # Even if timeout, try to extract cookies anyway
            pass

        # Extract all cookies from the browser context
        all_cookies = context.cookies()

        # Filter to DefectDojo domain cookies
        domain_cookies = [
            c for c in all_cookies
            if domain in c.get("domain", "")
        ]

        browser.close()

    if not domain_cookies:
        print("ERROR: No cookies found for DefectDojo domain after login.", file=sys.stderr)
        print("Make sure you completed the Google login in the browser.", file=sys.stderr)
        sys.exit(1)

    iap_cookies = [c for c in domain_cookies if "GCP_IAA" in c["name"] or "GCP_IAP" in c["name"]]
    print(f"Extracted {len(domain_cookies)} cookies ({len(iap_cookies)} IAP-specific)")

    cookie_file = _save_cookies(domain_cookies, domain)
    print(f"Cookies saved to {cookie_file}")

    # Validate
    if _validate_cookies(cookie_file, dd_url):
        print("IAP authentication validated successfully.")
    else:
        print("WARNING: Cookie validation inconclusive — may still work with DEFECTDOJO_TOKEN.")

    return cookie_file


def get_iap_cookies() -> Optional[str]:
    """
    Get IAP cookie file for curl -b.

    1. Returns cached cookies if still valid
    2. Otherwise launches Playwright browser for login

    Returns path to Netscape cookie file, or None if DEFECTDOJO_URL not set.
    """
    url = os.environ.get("DEFECTDOJO_URL", "").strip().rstrip("/")
    if not url:
        return None

    # 1. Try cached cookies
    cached = get_cached_cookies()
    if cached:
        return cached

    # 2. Browser login flow
    return browser_login(url)


def clear_cache() -> None:
    """Remove cached IAP cookies."""
    for f in [COOKIE_CACHE_FILE, COOKIE_META_FILE]:
        if f.exists():
            f.unlink()
    print("IAP cookie cache cleared.")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--clear":
        clear_cache()
        sys.exit(0)

    if len(sys.argv) > 1 and sys.argv[1] == "--status":
        cached = get_cached_cookies()
        if cached:
            meta = json.loads(COOKIE_META_FILE.read_text())
            remaining = int(meta["expires_at"] - time.time())
            print(f"Cached cookies valid for {remaining}s")
            print(f"Domain: {meta.get('domain')}")
            print(f"Cookies: {', '.join(meta.get('cookie_names', []))}")
        else:
            print("No valid cached cookies.")
        sys.exit(0)

    # Default: get cookies (from cache or browser login)
    dd_url = os.environ.get("DEFECTDOJO_URL", "").strip().rstrip("/")
    if not dd_url:
        print("ERROR: DEFECTDOJO_URL must be set.", file=sys.stderr)
        sys.exit(1)

    cookie_file = get_iap_cookies()
    if cookie_file:
        print(f"\nCookie file: {cookie_file}")
    else:
        print("No IAP cookies obtained.")
        sys.exit(1)
